



multid:
  dataSource:
        dataSourceName: default
        url: jdbc:mysql://localhost:3306/dmxt?useUnicode=true&characterEncoding=UTF-8
        username: leach
        password: leach
  dataSources:
      - dataSourceName: test1
        url: jdbc:mysql://localhost:3306/one?useUnicode=true&characterEncoding=UTF-8
        username: leach
        password: leach
